// spotless:off
package frc.robot;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
// If the 2 imports above cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj BL_V2 = new ChoreoTraj(
        "BL_V2",
        OptionalInt.empty(),
        14.3701,
        new Pose2d(4.47127, 7.6249, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(7.63406, 7.44578, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj BL_V2$0 = new ChoreoTraj(
        "BL_V2",
        OptionalInt.of(0),
        3.33756,
        new Pose2d(4.47127, 7.6249, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(6.79825, 4.8878, Rotation2d.fromRadians(-2.63416))
    );
    public static final ChoreoTraj BL_V2$1 = new ChoreoTraj(
        "BL_V2",
        OptionalInt.of(1),
        1.4520400000000002,
        new Pose2d(6.79825, 4.8878, Rotation2d.fromRadians(-2.63416)),
        new Pose2d(2.85297, 5.55197, Rotation2d.fromRadians(2.29389))
    );
    public static final ChoreoTraj BL_V2$2 = new ChoreoTraj(
        "BL_V2",
        OptionalInt.of(2),
        5.567740000000001,
        new Pose2d(2.85297, 5.55197, Rotation2d.fromRadians(2.29389)),
        new Pose2d(7.48475, 5.65455, Rotation2d.fromRadians(1.80932))
    );
    public static final ChoreoTraj BL_V2$3 = new ChoreoTraj(
        "BL_V2",
        OptionalInt.of(3),
        1.4472699999999996,
        new Pose2d(7.48475, 5.65455, Rotation2d.fromRadians(1.80932)),
        new Pose2d(2.86849, 5.55974, Rotation2d.fromRadians(2.29389))
    );
    public static final ChoreoTraj BL_V2$4 = new ChoreoTraj(
        "BL_V2",
        OptionalInt.of(4),
        2.5654900000000005,
        new Pose2d(2.86849, 5.55974, Rotation2d.fromRadians(2.29389)),
        new Pose2d(7.63406, 7.44578, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj hblueqin_left = new ChoreoTraj(
        "hblueqin_left",
        OptionalInt.empty(),
        11.92549,
        new Pose2d(4.42124, 7.62197, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(2.8064, 5.45107, Rotation2d.fromRadians(2.58309))
    );
    public static final ChoreoTraj hblueqin_left$0 = new ChoreoTraj(
        "hblueqin_left",
        OptionalInt.of(0),
        4.85774,
        new Pose2d(4.42124, 7.62197, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(2.79088, 5.45884, Rotation2d.fromRadians(2.58309))
    );
    public static final ChoreoTraj hblueqin_left$1 = new ChoreoTraj(
        "hblueqin_left",
        OptionalInt.of(1),
        7.06775,
        new Pose2d(2.79088, 5.45884, Rotation2d.fromRadians(2.58309)),
        new Pose2d(2.8064, 5.45107, Rotation2d.fromRadians(2.58309))
    );
    public static final ChoreoTraj hbluesteal_left = new ChoreoTraj(
        "hbluesteal_left",
        OptionalInt.empty(),
        11.81782,
        new Pose2d(4.4596, 7.6243, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(2.86849, 5.51317, Rotation2d.fromRadians(2.26893))
    );
    public static final ChoreoTraj hblue_nobump = new ChoreoTraj(
        "hblue_nobump",
        OptionalInt.empty(),
        4.75088,
        new Pose2d(4.48289, 7.6243, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(3.11686, 7.28279, Rotation2d.fromRadians(2.0944))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("BL_V2", BL_V2),
        Map.entry("BL_V2$0", BL_V2$0),
        Map.entry("BL_V2$1", BL_V2$1),
        Map.entry("BL_V2$2", BL_V2$2),
        Map.entry("BL_V2$3", BL_V2$3),
        Map.entry("BL_V2$4", BL_V2$4),
        Map.entry("hblueqin_left", hblueqin_left),
        Map.entry("hblueqin_left$0", hblueqin_left$0),
        Map.entry("hblueqin_left$1", hblueqin_left$1),
        Map.entry("hbluesteal_left", hbluesteal_left),
        Map.entry("hblue_nobump", hblue_nobump)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
// spotless:on
