
package frc.robot;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj h1 = new ChoreoTraj(
	    "h1",
	    OptionalInt.empty(),
	    5.28839,
	    new Pose2d(4.671, 7.405, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(2.842, 5.642, Rotation2d.fromRadians(-2.256))
	);
	public static final ChoreoTraj p2 = new ChoreoTraj(
	    "p2",
	    OptionalInt.empty(),
	    2.69285,
	    new Pose2d(3.392, 6.362, Rotation2d.fromRadians(-1.088)),
	    new Pose2d(3.008, 5.243, Rotation2d.fromRadians(-0.655))
	);
	public static final ChoreoTraj p3 = new ChoreoTraj(
	    "p3",
	    OptionalInt.empty(),
	    3.12431,
	    new Pose2d(3.533, 6.34, Rotation2d.fromRadians(-3.131)),
	    new Pose2d(2.397, 3.793, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj p3$0 = new ChoreoTraj(
	    "p3",
	    OptionalInt.of(0),
	    1.02383,
	    new Pose2d(3.533, 6.34, Rotation2d.fromRadians(-3.131)),
	    new Pose2d(1.468, 6.042, Rotation2d.fromRadians(-3.095))
	);
	public static final ChoreoTraj p3$1 = new ChoreoTraj(
	    "p3",
	    OptionalInt.of(1),
	    1.0153999999999999,
	    new Pose2d(1.468, 6.042, Rotation2d.fromRadians(-3.095)),
	    new Pose2d(2.073, 5.126, Rotation2d.fromRadians(-0.424))
	);
	public static final ChoreoTraj p3$2 = new ChoreoTraj(
	    "p3",
	    OptionalInt.of(2),
	    1.08508,
	    new Pose2d(2.073, 5.126, Rotation2d.fromRadians(-0.424)),
	    new Pose2d(2.397, 3.793, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj p4 = new ChoreoTraj(
	    "p4",
	    OptionalInt.empty(),
	    8.3262,
	    new Pose2d(3.514, 5.621, Rotation2d.fromRadians(-0.967)),
	    new Pose2d(2.695, 2.671, Rotation2d.fromRadians(0.657))
	);
	public static final ChoreoTraj p4$0 = new ChoreoTraj(
	    "p4",
	    OptionalInt.of(0),
	    2.27641,
	    new Pose2d(3.514, 5.621, Rotation2d.fromRadians(-0.967)),
	    new Pose2d(7.665, 5.922, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj p4$1 = new ChoreoTraj(
	    "p4",
	    OptionalInt.of(1),
	    3.15213,
	    new Pose2d(7.665, 5.922, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(7.531, 2.898, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj p4$2 = new ChoreoTraj(
	    "p4",
	    OptionalInt.of(2),
	    2.89766,
	    new Pose2d(7.531, 2.898, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(2.695, 2.671, Rotation2d.fromRadians(0.657))
	);
	public static final ChoreoTraj p6 = new ChoreoTraj(
	    "p6",
	    OptionalInt.empty(),
	    7.4034,
	    new Pose2d(3.514, 5.621, Rotation2d.fromRadians(-0.967)),
	    new Pose2d(3.514, 5.621, Rotation2d.fromRadians(-0.967))
	);
	public static final ChoreoTraj p6$0 = new ChoreoTraj(
	    "p6",
	    OptionalInt.of(0),
	    2.51224,
	    new Pose2d(3.514, 5.621, Rotation2d.fromRadians(-0.967)),
	    new Pose2d(7.859, 7.029, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj p6$1 = new ChoreoTraj(
	    "p6",
	    OptionalInt.of(1),
	    2.5592799999999998,
	    new Pose2d(7.859, 7.029, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(7.533, 5.936, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj p6$2 = new ChoreoTraj(
	    "p6",
	    OptionalInt.of(2),
	    2.331880000000001,
	    new Pose2d(7.533, 5.936, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(3.514, 5.621, Rotation2d.fromRadians(-0.967))
	);
	public static final ChoreoTraj p6_mirror = new ChoreoTraj(
	    "p6_mirror",
	    OptionalInt.empty(),
	    7.74978,
	    new Pose2d(3.514, 2.448, Rotation2d.fromRadians(0.967)),
	    new Pose2d(3.514, 2.448, Rotation2d.fromRadians(0.967))
	);
	public static final ChoreoTraj p6_mirror$0 = new ChoreoTraj(
	    "p6_mirror",
	    OptionalInt.of(0),
	    2.34956,
	    new Pose2d(3.514, 2.448, Rotation2d.fromRadians(0.967)),
	    new Pose2d(7.665, 2.147, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj p6_mirror$1 = new ChoreoTraj(
	    "p6_mirror",
	    OptionalInt.of(1),
	    3.0504700000000002,
	    new Pose2d(7.665, 2.147, Rotation2d.fromRadians(1.571)),
	    new Pose2d(7.665, 2.147, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj p6_mirror$2 = new ChoreoTraj(
	    "p6_mirror",
	    OptionalInt.of(2),
	    2.3497500000000002,
	    new Pose2d(7.665, 2.147, Rotation2d.fromRadians(1.571)),
	    new Pose2d(3.514, 2.448, Rotation2d.fromRadians(0.967))
	);
	public static final ChoreoTraj t5 = new ChoreoTraj(
	    "t5",
	    OptionalInt.empty(),
	    8.71545,
	    new Pose2d(3.514, 5.621, Rotation2d.fromRadians(-0.967)),
	    new Pose2d(2.695, 2.671, Rotation2d.fromRadians(0.657))
	);
	public static final ChoreoTraj t5$0 = new ChoreoTraj(
	    "t5",
	    OptionalInt.of(0),
	    1.69488,
	    new Pose2d(3.514, 5.621, Rotation2d.fromRadians(-0.967)),
	    new Pose2d(7.665, 5.922, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj t5$1 = new ChoreoTraj(
	    "t5",
	    OptionalInt.of(1),
	    3.15213,
	    new Pose2d(7.665, 5.922, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(7.531, 2.898, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj t5$2 = new ChoreoTraj(
	    "t5",
	    OptionalInt.of(2),
	    3.8684400000000005,
	    new Pose2d(7.531, 2.898, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(2.695, 2.671, Rotation2d.fromRadians(0.657))
	);
	public static final ChoreoTraj test = new ChoreoTraj(
	    "test",
	    OptionalInt.empty(),
	    2.49981,
	    new Pose2d(7.281, 6.789, Rotation2d.fromRadians(0)),
	    new Pose2d(7.281, 4.041, Rotation2d.fromRadians(-3.142))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("h1", h1),
		Map.entry("p2", p2),
		Map.entry("p3", p3),
		Map.entry("p3$0", p3$0),
		Map.entry("p3$1", p3$1),
		Map.entry("p3$2", p3$2),
		Map.entry("p4", p4),
		Map.entry("p4$0", p4$0),
		Map.entry("p4$1", p4$1),
		Map.entry("p4$2", p4$2),
		Map.entry("p6", p6),
		Map.entry("p6$0", p6$0),
		Map.entry("p6$1", p6$1),
		Map.entry("p6$2", p6$2),
		Map.entry("p6_mirror", p6_mirror),
		Map.entry("p6_mirror$0", p6_mirror$0),
		Map.entry("p6_mirror$1", p6_mirror$1),
		Map.entry("p6_mirror$2", p6_mirror$2),
		Map.entry("t5", t5),
		Map.entry("t5$0", t5$0),
		Map.entry("t5$1", t5$1),
		Map.entry("t5$2", t5$2),
		Map.entry("test", test)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
